### ISSUE TITLE
MakingFilesR.ipynb notebook is corrupted

### ISSUE THREAD

**Issue by jpuritz** [ksil91/Ostrea_PopStructure#1]
Github will no longer load MakingFilesR.ipynb.  I also tried running it locally and it eventually fails.  It stops rendering after

# Outlier

**Comment by ksil91** [comment]
I checked this on both Windows and Linux with Chrome and FierFox, and it rendered fine for me. Are you using a Mac? What browser are you trying to view it with Github, and what version of Jupyter Notebook/Lab are you trying to run it locally?

The notebook actually ended on the line "Outlier", which I've now changed to make it clearer when the notebook ends.

**Comment by jpuritz** [comment]
I was on Safari on OS X and was working with the latest version of Jupyter notebooks on OS X.  However, my whole class tried to render the notebook on GitHub using a variety of computers, OS, and internet browsers.  I'm not sure if this was a GitHub issue that was temporary because I had checked before my class and it worked.  

Either way the new changes appear to be working for me.  

Thanks!

**Comment by ksil91** [comment]
@jpuritz This issue popped up again for me, so I've added a note on the Readme. If Github has problems rendering, you should always be able to paste the URL into https://nbviewer.jupyter.org/ and view the notebook. Will look into other reproducible paper repository options in the future....

**Comment by jpuritz** [comment]
That's a bummer.   I've yet to find a perfect solution for this.  I like Rmarkdown, but it has trouble actually running `BASH` scripts without producing errors.
